SCHEMA_REGISTRY = {
    "vehicle_fault_master_ravi_v2": {
        "description": "Fault episodes per vehicle with severity, resolution, and customer scope",
        "columns": [
            "uniqueid",
            "vehicle_number",
            "customer_name",
            "dtc_code",
            "system",
            "subsystem",
            "severity_level",
            "first_ts",
            "last_ts",
            "event_date",
            "occurrence_count",
            "resolution_time_sec",
            "is_resolved",
            "driver_related",
            "vehicle_health_score",
        ],
        "use_cases": [
            "vehicle faults",
            "fault history",
            "root cause",
            "cooccurrence",
            "fault frequency",
            "severity",
        ],
        "filters": {
            "customer_name": "strict_when_present",
            "vehicle_number": "optional",
            "dtc_code": "optional",
        },
        "joins": {
            "uniqueid": "vehicle_health_summary_ravi_v2.uniqueid",
            "dtc_code": "dtc_master_ravi_v2.dtc_code",
        },
        "priority": "raw",
    },
    "fleet_dtc_distribution_ravi_v2": {
        "description": "Pre-aggregated fleet DTC distribution and impact metrics",
        "columns": [
            "dtc_code",
            "description",
            "system",
            "subsystem",
            "severity_level",
            "vehicles_affected",
            "active_vehicles",
            "total_occurrences",
            "total_episodes",
            "avg_resolution_time",
            "driver_related_count",
        ],
        "use_cases": [
            "top dtc",
            "fleet distribution",
            "fleet dtc",
            "common dtc",
        ],
        "filters": {
            "customer_name": "not_available",
        },
        "joins": {
            "dtc_code": "dtc_master_ravi_v2.dtc_code",
        },
        "priority": "aggregated",
    },
    "fleet_health_summary_ravi_v2": {
        "description": "Fleet-wide summary KPIs",
        "columns": [
            "total_vehicles",
            "vehicles_with_active_faults",
            "vehicles_with_critical_faults",
            "driver_related_faults",
            "fleet_health_score",
            "most_common_dtc",
            "most_common_system",
            "active_fault_trend",
        ],
        "use_cases": [
            "fleet health",
            "fleet overview",
            "kpi",
            "summary",
        ],
        "filters": {
            "customer_name": "not_available",
        },
        "joins": {},
        "priority": "aggregated",
    },
    "fleet_fault_trends_ravi_v2": {
        "description": "Daily trend series for fleet faults and health",
        "columns": [
            "date",
            "active_faults",
            "new_faults",
            "resolved_faults",
            "driver_related_faults",
            "fleet_health_score",
        ],
        "use_cases": [
            "trend",
            "time series",
            "daily",
            "over time",
        ],
        "filters": {
            "date": "range",
        },
        "joins": {},
        "priority": "aggregated",
    },
    "fleet_system_health_ravi_v2": {
        "description": "Fleet risk and fault metrics by system",
        "columns": [
            "system",
            "vehicles_affected",
            "active_faults",
            "critical_faults",
            "risk_score",
            "trend",
        ],
        "use_cases": [
            "system health",
            "risk by system",
            "engine issues",
            "emission issues",
        ],
        "filters": {
            "customer_name": "not_available",
        },
        "joins": {},
        "priority": "aggregated",
    },
    "vehicle_health_summary_ravi_v2": {
        "description": "Vehicle-level health summary and issue flags",
        "columns": [
            "uniqueid",
            "vehicle_number",
            "customer_name",
            "vehicle_health_score",
            "active_fault_count",
            "critical_fault_count",
            "total_episodes",
            "episodes_last_30_days",
            "avg_resolution_time",
            "driver_related_faults",
            "most_common_dtc",
            "has_engine_issue",
            "has_emission_issue",
            "has_safety_issue",
            "has_electrical_issue",
        ],
        "use_cases": [
            "vehicle health",
            "vehicle summary",
            "maintenance",
            "critical faults",
        ],
        "filters": {
            "customer_name": "strict_when_present",
            "vehicle_number": "optional",
        },
        "joins": {
            "uniqueid": "vehicle_fault_master_ravi_v2.uniqueid",
            "most_common_dtc": "dtc_master_ravi_v2.dtc_code",
        },
        "priority": "aggregated",
    },
    "maintenance_priority_ravi_v2": {
        "description": "Pre-ranked maintenance priorities by vehicle and fault",
        "columns": [
            "uniqueid",
            "vehicle_number",
            "dtc_code",
            "description",
            "severity_level",
            "fault_duration_sec",
            "episodes_last_30_days",
            "maintenance_priority_score",
            "recommended_action",
        ],
        "use_cases": [
            "maintenance priority",
            "urgent maintenance",
            "action plan",
        ],
        "filters": {
            "customer_name": "via_join_vehicle_health_summary",
            "vehicle_number": "optional",
        },
        "joins": {
            "uniqueid": "vehicle_health_summary_ravi_v2.uniqueid",
            "dtc_code": "dtc_master_ravi_v2.dtc_code",
        },
        "priority": "aggregated",
    },
    "dtc_fleet_impact_ravi_v2": {
        "description": "Fleet impact metrics by DTC code",
        "columns": [
            "dtc_code",
            "system",
            "subsystem",
            "vehicles_affected",
            "active_vehicles",
            "avg_resolution_time",
            "driver_related_ratio",
            "fleet_risk_score",
        ],
        "use_cases": [
            "dtc impact",
            "risk score",
            "fleet risk",
        ],
        "filters": {
            "customer_name": "not_available",
        },
        "joins": {
            "dtc_code": "dtc_master_ravi_v2.dtc_code",
        },
        "priority": "aggregated",
    },
    "dtc_cooccurrence_ravi_v2": {
        "description": "Co-occurrence pairs for DTC codes",
        "columns": [
            "dtc_code_a",
            "dtc_code_b",
            "cooccurrence_count",
            "vehicles_affected",
            "avg_time_gap_sec",
            "last_seen_ts",
        ],
        "use_cases": [
            "cooccurrence",
            "fault correlation",
            "root cause pattern",
        ],
        "filters": {
            "dtc_code": "optional",
        },
        "joins": {
            "dtc_code_a": "dtc_master_ravi_v2.dtc_code",
            "dtc_code_b": "dtc_master_ravi_v2.dtc_code",
        },
        "priority": "aggregated",
    },
    "dtc_master_ravi_v2": {
        "description": "Reference DTC knowledge base",
        "columns": [
            "dtc_code",
            "system",
            "subsystem",
            "description",
            "primary_cause",
            "secondary_causes",
            "symptoms",
            "impact_if_unresolved",
            "severity_level",
            "safety_risk_level",
            "action_required",
            "recommended_preventive_action",
        ],
        "use_cases": [
            "dtc details",
            "symptoms",
            "causes",
            "repair guidance",
        ],
        "filters": {
            "dtc_code": "required_for_lookup",
        },
        "joins": {},
        "priority": "dimension",
    },
}
